# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bizflyctl < Formula
  desc " Command Line for Bizfly Cloud."
  homepage "https://github.com/bizflycloud/bizflyctl"
  version "v0.2.18"

  on_macos do
    url "https://github.com/bizflycloud/bizflyctl/releases/download/v0.2.18/bizflyctl_Darwin_all.tar.gz"
    sha256 "9eb5f793a2d5fbb8e32e0029995b35ee4340ab4e931995af3234e2b5046a5b28"

    def install
      bin.install "bizfly"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/bizflycloud/bizflyctl/releases/download/v0.2.18/bizflyctl_Linux_armv6.tar.gz"
      sha256 "9eb5f793a2d5fbb8e32e0029995b35ee4340ab4e931995af3234e2b5046a5b28"

      def install
        bin.install "bizfly"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/bizflycloud/bizflyctl/releases/download/v0.2.18/bizflyctl_Linux_arm64.tar.gz"
      sha256 "9eb5f793a2d5fbb8e32e0029995b35ee4340ab4e931995af3234e2b5046a5b28"

      def install
        bin.install "bizfly"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/bizflycloud/bizflyctl/releases/download/v0.2.18/bizflyctl_Linux_x86_64.tar.gz"
      sha256 "9eb5f793a2d5fbb8e32e0029995b35ee4340ab4e931995af3234e2b5046a5b28"

      def install
        bin.install "bizfly"
      end
    end
  end
end
