# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bizflyctl < Formula
  desc " Command Line for Bizfly Cloud."
  homepage "https://github.com/bizflycloud/bizflyctl"
  version "0.2.22"

  on_macos do
    url "https://github.com/bizflycloud/bizflyctl/releases/download/v0.2.22/bizflyctl_Darwin_all.tar.gz"
    sha256 "19230f48b848de57c2e13c979fa416d0c8537035626cccd4896634241b0a937b"

    def install
      bin.install "bizfly"
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bizflycloud/bizflyctl/releases/download/v0.2.22/bizflyctl_Linux_x86_64.tar.gz"
        sha256 "27fb8a1dcf19bb506136d836ca4563aac63e423168b304bbb8b14a7844e8153b"

        def install
          bin.install "bizfly"
        end
      end
    end
    on_arm do
      if !Hardware::CPU.is_64_bit?
        url "https://github.com/bizflycloud/bizflyctl/releases/download/v0.2.22/bizflyctl_Linux_armv6.tar.gz"
        sha256 "80a1b99a224c53c448cfb89c87d1ae896ce418568d521b7b160592c42f9b159d"

        def install
          bin.install "bizfly"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bizflycloud/bizflyctl/releases/download/v0.2.22/bizflyctl_Linux_arm64.tar.gz"
        sha256 "3ad8a420290a90bd58aa2adb033f77ec5d808c27fb32e67399da75d1880d9fe0"

        def install
          bin.install "bizfly"
        end
      end
    end
  end
end
